name: DVC CI/CD Pipeline with Streamlit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    env:
      GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}  # GCS service account JSON string
      STREAMLIT_APP_NAME: ${{ secrets.STREAMLIT_APP_NAME }} 
      OPENPAGERANK_API_KEY: ${{ secrets.OPENPAGERANK_API_KEY }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      GOOGLE_CSE_ID: ${{ secrets.GOOGLE_CSE_ID }}

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install 'dvc[gs]'  # Enables Google Storage remote support

    - name: Configure GCS Remote for DVC
      run: |
        mkdir -p ~/.config/gcloud
        echo "${GCP_SERVICE_ACCOUNT_KEY}" > gcloud-key.json
        dvc remote modify gcsremote credentialpath gcloud-key.json
        dvc remote default gcsremote

    - name: Pull Dataset (if not present)
      run: dvc pull -r gcsremote

    - name: Train Model
      run: python train.py

    - name: Configure Git identity
      run: |
        git config --global user.email "gaurav.vjadhav01@gmail.com"
        git config --global user.name "Gaurav Jadhav"

    - name: Track Final Model with DVC
      run: |
        dvc add models/xgb_pipeline.pkl
        git add models/xgb_pipeline.pkl.dvc models/.gitignore
        git commit -m "Auto-track updated model"
        dvc push

    - name: Deploy to Streamlit 
      run: echo "✅ Ready for Streamlit deployment"
